package libvsw

// WipeStr is string array holds wipe type names.
var WipeStr []string = []string{
	"horizontal",
	"horizontal_r",
	"vertical",
	"vertical_r",
	"horizontal_slide",
	"horizontal_slide_r",
	"vertical_slide",
	"vertical_slide_r",
	"horizontal_double_slide",
	"horizontal_double_slide_r",
	"vertical_double_slide",
	"vertical_double_slide_r",
	"square_top_left",
	"square_top_left_r",
	"square_top",
	"square_top_r",
	"square_top_right",
	"square_top_right_r",
	"square_center_left",
	"square_center_left_r",
	"square_center",
	"square_center_r",
	"square_center_right",
	"square_center_right_r",
	"square_bottom_left",
	"square_bottom_left_r",
	"square_bottom",
	"square_bottom_r",
	"square_bottom_right",
	"square_bottom_right_r",
}
